'use client';
import { FormEvent, useState } from 'react';

const doubts=['提示された金額が高いのか安いのか分からない','「一式」と書かれていて内容が分からない','使う塗料が本当に適切か分からない','訪問販売から契約を急かされている','他社と比較したいが見方が分からない','追加料金が発生しないか不安'];
const checks=[['塗装面積','面積の根拠と数量'],['足場費用','建物条件に合う費用'],['塗料','メーカー・商品名'],['3回塗り','下・中・上塗り'],['下地処理','劣化に必要な処置'],['付帯部','雨どい・破風の範囲'],['追加工事','発生条件の明示'],['保証内容','対象・期間・条件']];
const faqs=[['他社の見積書でも見てもらえますか？','はい。他社様の見積書も確認し、確認しておきたい点を分かりやすくお伝えします。'],['診断後に契約する必要はありますか？','ありません。見積もり内容を理解するためのご相談としてご利用ください。'],['営業電話はありますか？','ご相談内容に沿ったご連絡を行います。不要なご案内はいたしません。'],['相談だけでも大丈夫ですか？','もちろんです。契約前の不安や、業者へ質問するポイントの確認だけでもご相談いただけます。'],['見積書の個人情報はどう扱われますか？','診断のためにお預かりした情報は、相談対応の目的で取り扱います。住所や氏名を伏せていただいても構いません。'],['現地調査にはどのくらい時間がかかりますか？','建物の状態や敷地条件によって異なります。事前に目安をご案内します。'],['対応エリアはどこですか？','東京都を中心とした対応地域について、まずはお気軽にお問い合わせください。']];
const Arrow=()=> <span className="arrow">→</span>;
const Heading=({tag,title,copy}:{tag:string,title:React.ReactNode,copy?:string})=><header className="heading"><p>{tag}</p><h2>{title}</h2>{copy&&<span>{copy}</span>}</header>;

export default function Home(){const [open,setOpen]=useState(-1);const [done,setDone]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();setDone(true)};return <main>
<header className="top"><a className="logo logoImage" href="#top"><img src="/gaihekipokke-logo.webp" alt="外壁ぽっけ"/></a><div><a className="tel" href="tel:0120546111"><small>お電話での相談</small>0120-546-111</a><a className="miniCta" href="#contact">無料診断をはじめる <Arrow/></a></div></header>
<section className="hero" id="top"><div className="heroText"><p className="tag">FREE ESTIMATE CHECK <b>相談無料</b></p><p className="area">● 東京都を中心に対応</p><h1>その外壁塗装の<br/><em>見積もり、</em><br/>本当に適正ですか？</h1><p>他社の見積書を送るだけ。塗装面積・塗料・工程・保証・追加費用を、分かりやすく確認します。</p><div className="badges"><span>見積もりだけでも可</span><span>LINE・電話・Web診断</span></div><a className="cta" href="#contact">見積もりを無料で診断する <Arrow/></a><small>無理な営業はいたしません。お気軽にご相談ください。</small></div><div className="heroArt"><img src="/estimate-hero.png" alt="見積書を確認する相談のイラスト"/><div className="stamp">✓<span>契約前に<br/>確認しよう</span></div><div className="paper"><b>外壁塗装 お見積書</b><i/><i/><i/><i/></div></div></section>
<div className="strip"><span>おうちの外壁のこと、もっと気軽に。</span><a href="#contact">カンタン見積もりも使えます <Arrow/></a></div>
<section className="section doubts"><Heading tag="BEFORE YOU SIGN" title={<>見積書を見ても、<br/><em>こんな不安はありませんか？</em></>}/><div className="doubtGrid">{doubts.map((x,i)=><article key={x}><b>0{i+1}</b><i>?</i><p>{x}</p></article>)}</div><p className="closing">大切な住まいのことだから。<br/><strong>「よく分からないまま」契約しないために、</strong><br/>まずは見積書の中身を一緒に確認しましょう。</p></section>
<section className="section checkSection"><Heading tag="WHAT WE CHECK" title={<>見積もり診断で<br/><em>確認する8つの項目</em></>} copy="金額だけでなく、工事内容と将来の安心まで。見積書に必要な情報がそろっているかを確認します。"/><div className="checkGrid">{checks.map(([x,y],i)=><article key={x}><b>0{i+1}</b><i>{['▣','⌂','◉','≡','⌁','⊞','＋','✓'][i]}</i><h3>{x}</h3><p>{y}</p></article>)}</div></section>
<section className="section result"><div><Heading tag="DIAGNOSIS RESULT" title={<>「どこを確認すべきか」を、<br/><em>具体的にお伝えします。</em></>}/><p>実際の見積書をもとに、適正と思われる項目・確認が必要な項目・記載が不足している項目を整理。業者へ聞くべき質問もご案内します。</p><div className="legend"><span><i/>適正と思われる項目</span><span><i/>確認が必要な項目</span><span><i/>記載不足の項目</span></div></div><aside><b>実際の診断事例を、個人情報を伏せたうえで掲載予定です。</b><div><i>⌁</i><strong>診断結果イメージ</strong><small>実績・許諾を確認後に公開します</small></div><small>※架空の見積書・診断結果は掲載していません。</small></aside></section>
<section className="section price"><Heading tag="HOW THE PRICE IS BUILT" title={<>外壁塗装の費用は、<br/><em>一律では決まりません。</em></>} copy="建物の状態や面積、必要な工程によって変わります。合計金額だけではなく、価格の構造を確認することが大切です。"/><div className="formula"><span>施工面積</span><b>+</b><span>足場</span><b>+</b><span>下地処理</span><b>+</b><span>塗料</span><b>+</b><span>付帯部</span><b>+</b><span>施工管理</span><b>=</b><strong>外壁塗装費用</strong></div><small>施工実績を確認後、坪数・塗料・工事範囲・工期・実際の契約金額を公開予定です。</small></section>
<section className="section works"><Heading tag="OUR WORKS" title="施工事例" copy="地域・建物の状態・ご提案内容が分かる施工事例を順次ご紹介します。"/><div><b>施工前・施工後の写真と、実績情報を確認後に掲載します</b><span>地域 / 築年数 / 劣化症状 / 塗料 / 工期 / 費用 / お悩みと提案理由</span></div><a href="https://www.gaihekipokke.jp/works" target="_blank" rel="noreferrer">外壁ぽっけの施工事例を見る <Arrow/></a></section>
<section className="section reason"><div className="illus"><i/><b/><span>写真で、<br/>分かりやすく。</span></div><div><Heading tag="WHY YUTAKA HOME" title={<>住まいのことを、<br/><em>きちんと理解して</em><br/>選べるように。</>}/><p>ユタカホームの実際の対応内容を確認のうえ、以下の情報を公開していきます。</p><ul>{['診断内容を写真で説明','見積もり項目を明確化','塗装が不要な場合も説明','施工工程を記録','アフターフォロー','地域対応力'].map(x=><li key={x}>✓ {x}</li>)}</ul><small>※サービス内容はヒアリング後に確定します。</small></div></section>
<section className="section people"><Heading tag="OUR PEOPLE" title={<>誰が来るのかが、<br/><em>見える安心。</em></>} copy="代表者・診断担当者・営業担当者・職人の紹介、保有資格・経験年数・仕事で大切にしていることを、実写とともに掲載予定です。"/><div>担当者・職人の情報を確認後に公開します</div></section>
<section className="section flow"><Heading tag="HOW IT WORKS" title="診断の流れ"/><div>{[['01','▤','見積書を撮影'],['02','↗','LINEまたはフォームで送信'],['03','⌕','担当者が内容を確認'],['04','✓','診断結果を回答'],['05','⌂','希望者のみ現地調査']].map(([a,b,c])=><article key={a}><small>{a}</small><i>{b}</i><h3>{c}</h3></article>)}</div></section>
<section className="section faq"><Heading tag="FAQ" title="よくある質問"/><div>{faqs.map(([q,a],i)=><article key={q}><button onClick={()=>setOpen(open===i?-1:i)}><span><b>Q.</b>{q}</span><i>{open===i?'−':'+'}</i></button>{open===i&&<p><b>A.</b>{a}</p>}</article>)}</div></section>
<section className="contact" id="contact"><div><Heading tag="FREE ESTIMATE CHECK" title={<>契約する前に、<br/><em>見積もりの内容を</em><br/>確認しませんか？</>}/><p>「これで進めていいのかな」という気持ちのままで契約しないために。まずは、お手元の見積書をお送りください。</p><nav><a href="#web">LINEで見積書を送る <Arrow/></a><a href="#web">カンタン見積もりを試す <Arrow/></a><a href="tel:0120546111">電話で相談する <Arrow/></a></nav></div><form id="web" onSubmit={submit}><h3>Webで無料診断を申し込む</h3>{done?<div className="thanks"><b>送信ありがとうございます。</b><span>内容を確認のうえ、ご連絡します。</span></div>:<><label>お名前<input required placeholder="例）山田 太郎"/></label><label>電話番号<input required type="tel" placeholder="例）090-1234-5678"/></label><label>ご相談内容<textarea placeholder="見積書で気になっていることをご記入ください"/></label><button className="cta">無料診断を申し込む <Arrow/></button><small>送信前に、個人情報の取り扱いをご確認ください。</small></>}</form></section>
<footer><a className="logo logoImage" href="#top"><img src="/gaihekipokke-logo.webp" alt="外壁ぽっけ"/></a><p>見積もり診断・外壁塗装のご相談<br/>株式会社ユタカホーム　0120-546-111</p><small>© 2026 外壁ぽっけ All Rights Reserved.</small></footer>
</main>}
